(function() {var implementors = {};
implementors["coaster"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"coaster/hardware/enum.HardwareType.html\" title=\"enum coaster::hardware::HardwareType\">HardwareType</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"coaster/frameworks/native/device/struct.Cpu.html\" title=\"struct coaster::frameworks::native::device::Cpu\">Cpu</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"coaster/frameworks/opencl/context/struct.Context.html\" title=\"struct coaster::frameworks::opencl::context::Context\">Context</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"coaster/frameworks/opencl/memory/struct.MemoryFlags.html\" title=\"struct coaster::frameworks::opencl::memory::MemoryFlags\">MemoryFlags</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"coaster/frameworks/opencl/queue/struct.QueueFlags.html\" title=\"struct coaster::frameworks::opencl::queue::QueueFlags\">QueueFlags</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"coaster/frameworks/cuda/context/struct.Context.html\" title=\"struct coaster::frameworks::cuda::context::Context\">Context</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
